# Generated by Django 4.0.4 on 2024-02-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nit',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Identificacion'),
        ),
    ]
