# Generated by Django 4.0.4 on 2024-02-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identificacion'),
        ),
    ]
