# Generated by Django 4.0.4 on 2024-02-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nit',
            field=models.CharField(max_length=20, unique=True, verbose_name='Identificacion'),
        ),
    ]
