# Generated by Django 4.0.4 on 2024-02-23 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('site', models.CharField(max_length=225)),
                ('hour', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('points', models.IntegerField()),
                ('students', models.ManyToManyField(related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activitie',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
