# Generated by Django 4.0.4 on 2024-02-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_participation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dias_semana',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], help_text='Selecciona los días de la semana', max_length=20, null=True),
        ),
    ]
