# Generated by Django 4.0.4 on 2024-02-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activityschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10),
        ),
    ]
