# Generated by Django 4.0.4 on 2024-02-24 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activityschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_schedule', to='activities.activity'),
        ),
        migrations.AlterUniqueTogether(
            name='activityschedule',
            unique_together={('activity', 'day', 'hour')},
        ),
    ]
