# Generated by Django 4.0.4 on 2024-02-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activityschedule_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
