# Generated by Django 4.0.4 on 2024-02-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_qr_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='hour_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='hour_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityschedule',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='activityschedule',
            unique_together={('activity', 'day', 'hour_start', 'hour_end')},
        ),
        migrations.RemoveField(
            model_name='activityschedule',
            name='hour',
        ),
    ]
