# Generated by Django 4.0.4 on 2024-02-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_activityschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='hour_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='hour_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='validate',
            field=models.BooleanField(),
        ),
    ]
