# Generated by Django 4.0.4 on 2024-02-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_activityschedule_hour_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='date',
            new_name='date_start',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='activityschedule',
            name='validate',
        ),
        migrations.AddField(
            model_name='participation',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='validate',
            field=models.BooleanField(default=False),
        ),
    ]
