# Generated by Django 4.0.4 on 2024-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_rename_date_participation_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='activities'),
        ),
    ]
