# Generated by Django 4.0.4 on 2024-02-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_pointsuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_date',
        ),
        migrations.DeleteModel(
            name='ActivitySchedule',
        ),
    ]
