# Generated by Django 4.0.4 on 2024-02-28 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0019_remove_activity_day_remove_activity_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to=settings.AUTH_USER_MODEL),
        ),
    ]
